### ISSUE TITLE
Generate temporary files into an extra folder?

### ISSUE THREAD

**Issue by marceltaeumel** [krono/swathesis#20]
Is it possible to not spoil the root folder of my document but to put aux, bbl, glo, log, lol, ... into a custom "aux" folder?

**Comment by krono** [comment]
very hard to do.

**Comment by krono** [comment]
MiKTeX has `--aux-directory` but TeXLive/Web2c has not.
`latexmk` can reuse `--aux-directory` and provides `-outdir` to put everything somewhere. You can then copy back the PDF from there.
