### ISSUE TITLE
\autoref with page number?

### ISSUE THREAD

**Issue by marceltaeumel** [krono/swathesis#34]
If the referenced figure is not in the same, previous, or next page, it would be great to add a page number:

![figure](https://cloud.githubusercontent.com/assets/5765308/19645755/a31633fe-99f6-11e6-96f7-f8e0fd1b8c86.png)

**Comment by krono** [comment]
you can use `\autopageref` but there's no (easy) facility to detect wether the ref is on the page as the fig.

Also, this is not common.

**Comment by marceltaeumel** [comment]
`... \autoref{fig:foo}\textsmall{(\autopageref{fig:foo})} ...`

`... \autoref{fig:foo}\textsmall{(p.\pageref{fig:foo})} ...`

This seems to be a good idiom: `... \autoref{fig:foo} on \autopageref{fig:foo} ...`

**Comment by krono** [comment]
Can close?
