### ISSUE TITLE
lstlisting has non-fixed width spaces

### ISSUE THREAD

**Issue by marceltaeumel** [krono/swathesis#35]
It is not possible to layout code in the default *lstlisting* environment like this due to spaces being shorter than the letters:

```Smalltalk
Transcript cr;
           show: 'foo'.
```

(Note that the `cr` is exactly above the `show`.)

This was my example:

```
methodsFrom(?classView, ?methodView) if
  hasMethod(forall, ?classView,
            exists, ?methodView),
  not( notHasMethod(exists, ?classView,
                    forall, ?methodView)).
```

**Comment by krono** [comment]
Doesn't `\lstset{columns=fixed}` work?

**Comment by marceltaeumel** [comment]
Well, maybe. I just found this default behaviour strange because I somewhat referred to the behavior of the *verbatim* enviroment.

Maybe we can change that in the thesis class?

**Comment by krono** [comment]
The not-completely-aligned is a deliberate choice.
`fixed` is default, (swathesis sets `fullflexible`)[https://github.com/krono/swathesis/blob/master/swa-listings.sty#L38].

**Comment by marceltaeumel** [comment]
Hmm... too bad. It gives you less control about the format/looks of your code snippet. This can impede readability. Especially since the font is set to monospaced. That combination feels weird.

**Comment by krono** [comment]
yeah, it depends. I decided for opt-out of fullflexible as it looked better that way in most theses handed to me.
closing for now
