### ISSUE TITLE
Thesis template does not compile on recent TeX Live (+ workaround)

### ISSUE THREAD

**Issue by f4lco** [krono/swathesis#41]
I would like to point out that it is not possible to compile the thesis template on a recent version of TeX Live, and to propose a temporary workaround.

```
$ swth create
...
$ swth go
Beware of Dragons!
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
! Package Listings Error: Numbers none unknown.

l.36 ...Error{Listings}{Numbers #1 unknown}\@ehc}}
! Emergency stop.
 ...
l.36 ...Error{Listings}{Numbers #1 unknown}\@ehc}}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on redacted.log.
INFO - This is Biber 2.12
INFO - Logfile is 'redacted.blg'
ERROR - Cannot find control file 'redacted.bcf'! - Did latex run successfully on your .tex file before you ran biber?
INFO - ERRORS: 1
Whoops
```
I suppose this is due to incompatible changes in dependent packages as per this [TeX StackExchange question](https://tex.stackexchange.com/questions/451532/recent-issues-with-lstlinebgrd-package-with-listings-after-the-latters-updates). Possible solution would be to update the `lstlinebgrd` package to cope with the changes in `listings`.

My current workaround this to downgrade the listings package using the TeX Live Utility, and to defer any changes to the setup until completion of my thesis ;) Apparently Rev. 37534 is operational. After the downgrade the document compiles.

![image](https://user-images.githubusercontent.com/29141485/54290970-250fe180-45ac-11e9-833c-d424eb6f7c39.png)

**Comment by krono** [comment]
It seems to be known without proper workaround.
I see no proper solution besides dropping it...

**Comment by f4lco** [comment]
To my understanding, patching `lstlinebgrd` is possible... 😂  I wonder if it was much of an effort for somebody proficient in Tex.

**Comment by krono** [comment]
Dear Issue, you have been a good issue. Sleep well
