### ISSUE TITLE
Bibliography in Table of Contents

### ISSUE THREAD

**Issue by f4lco** [krono/swathesis#44]
Possibly, it would be nice for the bibliography to appear in the table contents. Usually the bibliography takes up a few pages and is a good link target. I've seen other thesis including the bibliography in the ToC by default.

```diff
-\printbibliography
+\printbibliography[heading=bibintoc]
```

Do you have opinions on this?

**Comment by krono** [comment]
Thanks for the comment!

Yes, I sincerely believe the Bib does not belong to the TOC.

See koma-script guide (`texdoc scrguide` or `texdoc scrguien`) §3.23

**Comment by krono** [comment]
(Ein Link im pdf fände ich aber sinvoll…)

**Comment by f4lco** [comment]
Danke, wieder was gelernt 🙂  Dann ist entspricht mein Vorschlag zufällig genau dem Mittelweg / Grauzone, und lässt zu im PDF zu springen.

> Außerdem ist das Literaturverzeichnis letztlich nichts, was man selbst geschrieben hat. Deshalb verdient es allenfalls einen nicht nummerierten Eintrag im Inhaltsverzeichnis (...)
