### ISSUE TITLE
Better document how to add logos

### ISSUE THREAD

**Issue by ErikBrendel** [krono/swathesis#53]
_As a thesis author, I want to be informed about the option of adding the logo images to my thesis, in order to not miss this feature._

I personally was not sure about how to add the logo images to my thesis after the Studienreferat told me that I still need to add them (until Toni told me that the swa template already has some logic for them and I just need to put the files inside it), and I know of a student who even handed in the thesis without ever adding the logo images. The intended process here (e.g. where to get the images from and where to put them, so that they are incorporated automatically) should either be reworked, or at least communicated very actively to the author.

**Comment by krono** [comment]
If you're on the latest commit, this should be fixed…

**Comment by ErikBrendel** [comment]
Oh okay, then I guess it is just the old version that I used...
